[package]
name = "bag_of_holding"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abilities = { path = "./crates/abilities" }
anyhow = { version = "1.0.58", features = ["backtrace"] }
axum = { version = "0.5.10", features = ["headers", "http2", "multipart", "ws"] }
axum-extra = { version = "0.3.5", features = [
    "cookie-private",
    "cookie-signed",
    "erased-json",
    "spa",
    "typed-routing",
] }
axum-macros = "0.2.3"
axum-server = { version = "0.4.0", features = ["tls-rustls"] }
clap = { version = "3.2.6", features = ["derive", "env"] }
dice = { path = "./crates/dice" }
futures = "0.3.21"
hyper = { version = "0.14.19", features = ["full"] }
itertools = "0.10.3"
metrics = "0.19.0"
metrics-exporter-prometheus = "0.10.0"
mime = "0.3.16"
names = { path = "./crates/names" }
once_cell = "1.12.0"
rand = "0.8.5"
rand_utils = { path = "./crates/rand_utils" }
sentry = { version = "0.27.0", default-features = false, features = [
    "anyhow",
    "backtrace",
    "contexts",
    "panic",
    "reqwest",
    "rustls",
    "test",
    "tower",
    "tracing",
] }
sentry-tower = { version = "0.27.0", features = ["http"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
strum = { version = "0.24.1", features = ["derive"] }
tokio = { version = "1.19.2", features = ["full"] }
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.3.4", features = ["full"] }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }

[dev-dependencies]
statrs = "0.15.0"

[workspace]
members = ["crates/*"]

[profile.release]
lto = "thin"
