[package]
name = "bag_of_holding"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.4.5"
dice = { path = "./crates/dice" }
hyper = { version = "0.14.16", features = ["full"] }
mime = "0.3.16"
parking_lot = "0.12.0"
rand = "0.8.4"
rand_pcg = "0.3.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
tokio = { version = "1.16.1", features = ["full"] }
tower = "0.4.11"

[workspace]
members = ["crates/*"]
