[package]
name = "bag_of_holding"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.4.5", features = ["headers", "http2", "multipart", "ws"] }
axum-server = { version = "0.3.3", features = ["tls-rustls"] }
clap = { version = "3.1.0", features = ["derive"] }
dice = { path = "./crates/dice" }
hyper = { version = "0.14.17", features = ["full"] }
mime = "0.3.16"
rand = "0.8.5"
rand_pcg = "0.3.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tokio = { version = "1.17.0", features = ["full"] }
tower = { version = "0.4.12", features = ["full"] }
tower-http = { version = "0.2.2", features = ["full"] }
tracing = "0.1.30"
tracing-subscriber = { version = "0.3.8", features = ["env-filter"] }

[workspace]
members = ["crates/*"]
