[package]
name = "bag_of_holding"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abilities = { path = "./crates/abilities" }
anyhow = { version = "1.0.60", features = ["backtrace"] }
axum = { version = "0.5.14", features = [
    "headers",
    "http2",
    "multipart",
    "ws",
] }
axum-extra = { version = "0.3.6", features = [
    "cookie-private",
    "cookie-signed",
    "erased-json",
    "spa",
    "typed-routing",
] }
axum-macros = "0.2.3"
axum-server = { version = "0.4.1", features = ["tls-rustls"] }
characters = { path = "./crates/characters" }
clap = { version = "3.2.16", features = ["derive", "env"] }
dice = { path = "./crates/dice" }
futures = "0.3.21"
hyper = { version = "0.14.20", features = ["full"] }
itertools = "0.10.3"
metrics = "0.20.1"
metrics-exporter-prometheus = "0.11.0"
mime = "0.3.16"
names = { path = "./crates/names" }
once_cell = "1.13.0"
rand = "0.8.5"
rand_utils = { path = "./crates/rand_utils" }
sentry = { version = "0.27.0", default-features = false, features = [
    "anyhow",
    "backtrace",
    "contexts",
    "panic",
    "reqwest",
    "rustls",
    "test",
    "tower",
    "tracing",
] }
sentry-tower = { version = "0.27.0", features = ["http"] }
serde = { version = "1.0.141", features = ["derive"] }
serde_json = "1.0.82"
strum = { version = "0.24.1", features = ["derive"] }
tokio = { version = "1.20.1", features = ["full"] }
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.3.4", features = ["full"] }
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }

[dev-dependencies]
statrs = "0.15.0"

[workspace]
members = ["crates/*"]

[profile.release]
lto = "thin"
