[package]
name = "bag_of_holding"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.56", features = ["backtrace"] }
axum = { version = "0.4.8", features = ["headers", "http2", "multipart", "ws"] }
axum-server = { version = "0.3.3", features = ["tls-rustls"] }
clap = { version = "3.1.7", features = ["derive"] }
dice = { path = "./crates/dice" }
futures = "0.3.21"
hyper = { version = "0.14.18", features = ["full"] }
metrics = "0.18.1"
metrics-exporter-prometheus = "0.9.0"
mime = "0.3.16"
rand = "0.8.5"
rand_pcg = "0.3.1"
sentry = { version = "0.25.0", default-features = false, features = [
    "anyhow",
    "backtrace",
    "contexts",
    "panic",
    "reqwest",
    "rustls",
    "test",
    "tower",
    "tracing",
] }
sentry-tower = { version = "0.25.0", features = ["http"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
strum = { version = "0.24.0", features = ["derive"] }
tokio = { version = "1.17.0", features = ["full"] }
tower = { version = "0.4.12", features = ["full"] }
tower-http = { version = "0.2.5", features = ["full"] }
tracing = "0.1.32"
tracing-subscriber = { version = "0.3.9", features = ["env-filter"] }

[dev-dependencies]
statrs = "0.15.0"

[workspace]
members = ["crates/*"]

[profile.release]
lto = "thin"
