# fly.toml file generated for bag-of-holding on 2022-02-08T22:10:44+01:00

app = "bag-of-holding"

kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[env]
RUST_LOG = "info"

[experimental]
allowed_public_ports = []
auto_rollback = true

[metrics]
port = 9000
path = "/metrics"

[[services]]
http_checks = []
internal_port = 5000
processes = ["app"]
protocol = "tcp"
script_checks = []

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
