# fly.toml app configuration file generated for bag-of-holding on 2023-10-02T15:58:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bag-of-holding"
primary_region = "ams"
kill_signal = "SIGTERM"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  RUST_LOG = "info"
  SENTRY_DSN = "https://c21aaae10ee74c71aa81a04f03203f59@o251876.ingest.sentry.io/6243981"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"

[[metrics]]
  port = 9000
  path = "/metrics"
