use alignments::{Alignment, Attitude, Morality};

use crate::{Deity, Domain, Pantheon};

pub const CELTIC: &[Deity] = &[
    Deity {
        name: "The Daghdha",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Good),
        domains: &[Domain::Nature, Domain::Trickery],
        pantheon: Pantheon::Celtic,
        symbols: &["Bubbling cauldron", "shield"],
        titles: &["god of weather and crops"],
    },
    Deity {
        name: "Arawn",
        alignment: Alignment::new(Attitude::Neutral, Morality::Evil),
        domains: &[Domain::Life, Domain::Death],
        pantheon: Pantheon::Celtic,
        symbols: &["Black star on gray background"],
        titles: &["god of life and death"],
    },
    Deity {
        name: "Belenus",
        alignment: Alignment::new(Attitude::Neutral, Morality::Good),
        domains: &[Domain::Light],
        pantheon: Pantheon::Celtic,
        symbols: &["Solar disk and standing stones"],
        titles: &["god of sun, light, and warmth"],
    },
    Deity {
        name: "Brigantia",
        alignment: Alignment::new(Attitude::Neutral, Morality::Good),
        domains: &[Domain::Life],
        pantheon: Pantheon::Celtic,
        symbols: &["Footbridge"],
        titles: &["goddess of rivers and livestock"],
    },
    Deity {
        name: "Diancecht",
        alignment: Alignment::new(Attitude::Lawful, Morality::Good),
        domains: &[Domain::Life],
        pantheon: Pantheon::Celtic,
        symbols: &["Crossed oak and mistletoe branches"],
        titles: &["god of medicine and healing"],
    },
    Deity {
        name: "Dunatis",
        alignment: Alignment::new(Attitude::Neutral, Morality::Neutral),
        domains: &[Domain::Nature],
        pantheon: Pantheon::Celtic,
        symbols: &["Red sun-capped mountain peak"],
        titles: &["god of mountains and peaks"],
    },
    Deity {
        name: "Goibhniu",
        alignment: Alignment::new(Attitude::Neutral, Morality::Good),
        domains: &[Domain::Knowledge, Domain::Life],
        pantheon: Pantheon::Celtic,
        symbols: &["Giant mallet over sword"],
        titles: &["god of smiths and healing"],
    },
    Deity {
        name: "Lugh",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Neutral),
        domains: &[Domain::Knowledge, Domain::Life],
        pantheon: Pantheon::Celtic,
        symbols: &["Pair of long hands"],
        titles: &["god of arts, travel, and commerce"],
    },
    Deity {
        name: "Manannan mac Lir",
        alignment: Alignment::new(Attitude::Lawful, Morality::Neutral),
        domains: &[Domain::Nature, Domain::Tempest],
        pantheon: Pantheon::Celtic,
        symbols: &["Wave of white water on green"],
        titles: &["god of oceans and sea creatures"],
    },
    Deity {
        name: "Math Mathonwy",
        alignment: Alignment::new(Attitude::Neutral, Morality::Evil),
        domains: &[Domain::Knowledge],
        pantheon: Pantheon::Celtic,
        symbols: &["Staff"],
        titles: &["god of magic"],
    },
    Deity {
        name: "Morrigan",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Evil),
        domains: &[Domain::War],
        pantheon: Pantheon::Celtic,
        symbols: &["Two crossed spears"],
        titles: &["goddess of battle"],
    },
    Deity {
        name: "Nuada",
        alignment: Alignment::new(Attitude::Neutral, Morality::Neutral),
        domains: &[Domain::War],
        pantheon: Pantheon::Celtic,
        symbols: &["Silver hand on black background"],
        titles: &["god of war and warriors"],
    },
    Deity {
        name: "Oghma",
        alignment: Alignment::new(Attitude::Neutral, Morality::Good),
        domains: &[Domain::Knowledge],
        pantheon: Pantheon::Celtic,
        symbols: &["Unfurled scroll"],
        titles: &["god of speech and writing"],
    },
    Deity {
        name: "Silvanus",
        alignment: Alignment::new(Attitude::Neutral, Morality::Neutral),
        domains: &[Domain::Nature],
        pantheon: Pantheon::Celtic,
        symbols: &["Summer oak tree"],
        titles: &["god of nature and forests"],
    },
];
