use alignments::Alignment;

use crate::{Deity, Domain, Pantheon};

pub const DRAGONLANCE: &[Deity] = &[
    Deity {
        name: "Paladine",
        alignment: Alignment::LAWFUL_GOOD,
        domains: &[Domain::War],
        pantheon: Pantheon::Dragonlance,
        symbols: &["Silver triangle"],
        titles: &["god of rulers and guardians"],
    },
    Deity {
        name: "Branchala",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Light],
        pantheon: Pantheon::Dragonlance,
        symbols: &["Bard's harp"],
        titles: &["god of music"],
    },
    Deity {
        name: "Habbakuk",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Nature, Domain::Tempest],
        pantheon: Pantheon::Dragonlance,
        symbols: &["Blue bird"],
        titles: &["god of animal life and the sea"],
    },
    Deity {
        name: "Kiri-Jolith",
        alignment: Alignment::LAWFUL_GOOD,
        domains: &[Domain::War],
        pantheon: Pantheon::Dragonlance,
        symbols: &["Bison's horns"],
        titles: &["god of honor and war"],
    },
    Deity {
        name: "Majere",
        alignment: Alignment::LAWFUL_GOOD,
        domains: &[Domain::Knowledge],
        pantheon: Pantheon::Dragonlance,
        symbols: &["Copper spider"],
        titles: &["god of meditation and order"],
    },
    Deity {
        name: "Mishakal",
        alignment: Alignment::LAWFUL_GOOD,
        domains: &[Domain::Knowledge, Domain::Life],
        pantheon: Pantheon::Dragonlance,
        symbols: &["Blue infinity sign"],
        titles: &["goddess of healing"],
    },
    Deity {
        name: "Solinari",
        alignment: Alignment::LAWFUL_GOOD,
        domains: &[],
        pantheon: Pantheon::Dragonlance,
        symbols: &["White circle or sphere"],
        titles: &["god of good magic"],
    },
    Deity {
        name: "Gilean",
        alignment: Alignment::NEUTRAL,
        domains: &[Domain::Knowledge],
        pantheon: Pantheon::Dragonlance,
        symbols: &["Open book"],
        titles: &["god of knowledge"],
    },
    Deity {
        name: "Chislev",
        alignment: Alignment::NEUTRAL,
        domains: &[Domain::Nature],
        pantheon: Pantheon::Dragonlance,
        symbols: &["Feather"],
        titles: &["goddess of nature"],
    },
    Deity {
        name: "Reorx",
        alignment: Alignment::NEUTRAL,
        domains: &[Domain::Knowledge],
        pantheon: Pantheon::Dragonlance,
        symbols: &["Forging hammer"],
        titles: &["god of craft"],
    },
    Deity {
        name: "Shinare",
        alignment: Alignment::NEUTRAL,
        domains: &[Domain::Knowledge, Domain::Trickery],
        pantheon: Pantheon::Dragonlance,
        symbols: &["Griffon's wing"],
        titles: &["goddess of wealth and trade"],
    },
    Deity {
        name: "Sirrion",
        alignment: Alignment::NEUTRAL,
        domains: &[Domain::Nature],
        pantheon: Pantheon::Dragonlance,
        symbols: &["Multi-colored fire"],
        titles: &["god of fire and change"],
    },
    Deity {
        name: "Zivilyn",
        alignment: Alignment::NEUTRAL,
        domains: &[Domain::Knowledge],
        pantheon: Pantheon::Dragonlance,
        symbols: &["Great green or gold tree"],
        titles: &["god of wisdom"],
    },
    Deity {
        name: "Lunitari",
        alignment: Alignment::NEUTRAL,
        domains: &[],
        pantheon: Pantheon::Dragonlance,
        symbols: &["Red circle or sphere"],
        titles: &["goddess of neutral magic"],
    },
    Deity {
        name: "Takhisis",
        alignment: Alignment::LAWFUL_EVIL,
        domains: &[Domain::Death],
        pantheon: Pantheon::Dragonlance,
        symbols: &["Black crescent"],
        titles: &["goddess of night and hatred"],
    },
    Deity {
        name: "Chemosh",
        alignment: Alignment::LAWFUL_EVIL,
        domains: &[Domain::Death],
        pantheon: Pantheon::Dragonlance,
        symbols: &["Yellow skull"],
        titles: &["god of the undead"],
    },
    Deity {
        name: "Hiddukel",
        alignment: Alignment::CHAOTIC_EVIL,
        domains: &[Domain::Trickery],
        pantheon: Pantheon::Dragonlance,
        symbols: &["Broken merchant's scales"],
        titles: &["god of lies and greed"],
    },
    Deity {
        name: "Morgion",
        alignment: Alignment::NEUTRAL_EVIL,
        domains: &[Domain::Death],
        pantheon: Pantheon::Dragonlance,
        symbols: &["Hood with two red eyes"],
        titles: &["god of disease and secrecy"],
    },
    Deity {
        name: "Sargonnas",
        alignment: Alignment::LAWFUL_EVIL,
        domains: &[Domain::War],
        pantheon: Pantheon::Dragonlance,
        symbols: &["Stylized red condor"],
        titles: &["god of vengeance and fire"],
    },
    Deity {
        name: "Zeboim",
        alignment: Alignment::CHAOTIC_EVIL,
        domains: &[Domain::Tempest],
        pantheon: Pantheon::Dragonlance,
        symbols: &["Turtle shell"],
        titles: &["goddess of the sea and storms"],
    },
    Deity {
        name: "Nuitari",
        alignment: Alignment::LAWFUL_EVIL,
        domains: &[],
        pantheon: Pantheon::Dragonlance,
        symbols: &["Black circle or sphere"],
        titles: &["god of evil magic"],
    },
];
