use alignments::Alignment;

use crate::{Deity, Domain, Pantheon};

pub const DWARVEN: &[Deity] = &[
    Deity {
        name: "Abbathor",
        alignment: Alignment::NEUTRAL_EVIL,
        domains: &[Domain::Trickery],
        pantheon: Pantheon::Dwarven,
        symbols: &["Jeweled dagger, point-down"],
        titles: &["god of greed"],
    },
    Deity {
        name: "Berronar Truesilver",
        alignment: Alignment::LAWFUL_GOOD,
        domains: &[Domain::Life, Domain::Light],
        pantheon: Pantheon::Dwarven,
        symbols: &["Intertwined silver rings"],
        titles: &[
            "goddess of hearth and home",
            "goddess of honesty and faithfulness",
            "goddess of oaths, loyalty, and honor",
            "the Revered Mother",
            "goddess of hearth, home, and truth",
        ],
    },
    Deity {
        name: "Clangeddin Silverbeard",
        alignment: Alignment::LAWFUL_GOOD,
        domains: &[Domain::War],
        pantheon: Pantheon::Dwarven,
        symbols: &["Crossed silver battleaxes"],
        titles: &["god of war and valor", "god of war and strategy"],
    },
    Deity {
        name: "Dugmaren Brightmantle",
        alignment: Alignment::CHAOTIC_GOOD,
        domains: &[Domain::Knowledge],
        pantheon: Pantheon::Dwarven,
        symbols: &["Open book"],
        titles: &[
            "god of invention and discovery",
            "the Wandering Tinkerer",
            "the Gleam in the Eye",
            "god of discovery",
        ],
    },
    Deity {
        name: "Dumathoin",
        alignment: Alignment::NEUTRAL,
        domains: &[Domain::Death, Domain::Grave, Domain::Knowledge],
        pantheon: Pantheon::Dwarven,
        symbols: &[
            "Mountain silhouette with a central gemstone",
            "gemstone in a mountain",
        ],
        titles: &[
            "god of buried secrets",
            "god of buried wealth, mining, gems, and exploration",
            "the Keeper of Secrets under the Mountain",
            "the guardian of the dead",
        ],
    },
    Deity {
        name: "Gorm Gulthyn",
        alignment: Alignment::LAWFUL_GOOD,
        domains: &[Domain::War],
        pantheon: Pantheon::Dwarven,
        symbols: &["Bronze half-mask"],
        titles: &[
            "god of defense and vigilance",
            "Fire Eyes",
            "the Lord of the Bronze Mask",
            "the protector of dwarves",
            "god of vigilance",
        ],
    },
    Deity {
        name: "Haela Brightaxe",
        alignment: Alignment::CHAOTIC_GOOD,
        domains: &[Domain::War],
        pantheon: Pantheon::Dwarven,
        symbols: &[
            "Upright sword whose blade is spiraled in flame",
            "Upright sword with blade sheathed in flame",
        ],
        titles: &[
            "goddess of war-luck",
            "patron of dwarf fighters",
            "god of combat prowess and luck in battle",
        ],
    },
    Deity {
        name: "Hanseath",
        alignment: Alignment::CHAOTIC_NEUTRAL,
        domains: &[Domain::Trickery, Domain::War],
        pantheon: Pantheon::Dwarven,
        symbols: &["Beer stein"],
        titles: &["deity of festivity, brewing, and song"],
    },
    Deity {
        name: "Marthammor Duin",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Nature, Domain::Trickery],
        pantheon: Pantheon::Dwarven,
        symbols: &["Upright mace in front of a tall boot"],
        titles: &[
            "god of wanderers",
            "the traveler's god",
            "patron of expatriates and guides",
            "deity of lightning and roads",
            "god of explorers, wanderers, and the lost",
        ],
    },
    Deity {
        name: "Moradin",
        alignment: Alignment::LAWFUL_GOOD,
        domains: &[Domain::Forge, Domain::Knowledge],
        pantheon: Pantheon::Dwarven,
        symbols: &["Hammer and anvil"],
        titles: &[
            "god of creation",
            "god of \"dwarf-crafts\" (smithing and stonework)",
            "god of protection",
            "the Soulforger",
            "Dwarf-father",
            "All-father",
            "Primary deity of dwarves",
        ],
    },
    Deity {
        name: "Muamman Duathal",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Tempest],
        pantheon: Pantheon::Dwarven,
        symbols: &["Mace held in gauntlets"],
        titles: &["deity of storms and travel"],
    },
    Deity {
        name: "Mya",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Knowledge, Domain::Life],
        pantheon: Pantheon::Dwarven,
        symbols: &["A faceless mother figure"],
        titles: &["deity of clan, family, and wisdom"],
    },
    Deity {
        name: "Roknar",
        alignment: Alignment::NEUTRAL_EVIL,
        domains: &[Domain::Trickery],
        pantheon: Pantheon::Dwarven,
        symbols: &["Hands filled with coins"],
        titles: &["deity of lies and intrigue"],
    },
    Deity {
        name: "Sharindlar",
        alignment: Alignment::CHAOTIC_GOOD,
        domains: &[Domain::Life],
        pantheon: Pantheon::Dwarven,
        symbols: &["Burning needle"],
        titles: &[
            "goddess of healing, romantic love, and fertility",
            "Lady of Life and Mercy",
            "goddess of healing and love",
        ],
    },
    Deity {
        name: "Thard Harr",
        alignment: Alignment::CHAOTIC_GOOD,
        domains: &[Domain::Nature],
        pantheon: Pantheon::Dwarven,
        symbols: &["Two clawed guantlets"],
        titles: &["deity of wilderness and hunting"],
    },
    Deity {
        name: "Tharmekh\u{fb}l",
        alignment: Alignment::NEUTRAL,
        domains: &[Domain::Forge, Domain::Light],
        pantheon: Pantheon::Dwarven,
        symbols: &["Fiery axe"],
        titles: &["deity of fire, forges, and molten rock"],
    },
    Deity {
        name: "Thautam",
        alignment: Alignment::NEUTRAL,
        domains: &[Domain::Knowledge, Domain::Trickery],
        pantheon: Pantheon::Dwarven,
        symbols: &["Blindfold"],
        titles: &["deity of mysteries, darkness, and lost treasures"],
    },
    Deity {
        name: "Ulaa",
        alignment: Alignment::LAWFUL_GOOD,
        domains: &[Domain::Forge],
        pantheon: Pantheon::Dwarven,
        symbols: &["A miner's pick"],
        titles: &["deity of mining and quarrying"],
    },
    Deity {
        name: "Valkauna",
        alignment: Alignment::LAWFUL_NEUTRAL,
        domains: &[Domain::Grave, Domain::Life],
        pantheon: Pantheon::Dwarven,
        symbols: &["A silver ewer"],
        titles: &["deity of oaths, birth, aging, and death"],
    },
    Deity {
        name: "Vergadain",
        alignment: Alignment::NEUTRAL,
        domains: &[Domain::Trickery],
        pantheon: Pantheon::Dwarven,
        symbols: &[
            "Gold coin with the face of a dwarf",
            "Gold coin bearing a dwarf's face",
        ],
        titles: &[
            "god of luck and wealth",
            "god of thieves, luck, and chance",
            "god of commerce and negotiation",
            "the Merchant King",
        ],
    },
];
