use alignments::Alignment;

use crate::{Deity, Domain, Pantheon};

pub const EBERRON: &[Deity] = &[
    Deity {
        name: "Arawai",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Life, Domain::Nature],
        pantheon: Pantheon::Eberron,
        symbols: &["Sheaf of wheat tied with green ribbon"],
        titles: &["goddess of fertility"],
    },
    Deity {
        name: "Aureon",
        alignment: Alignment::LAWFUL_NEUTRAL,
        domains: &[Domain::Knowledge],
        pantheon: Pantheon::Eberron,
        symbols: &["Open tome"],
        titles: &["god of law and knowledge"],
    },
    Deity {
        name: "Balinor",
        alignment: Alignment::NEUTRAL,
        domains: &[Domain::Life, Domain::Nature],
        pantheon: Pantheon::Eberron,
        symbols: &["Pair of antlers"],
        titles: &["god of beasts and the hunt"],
    },
    Deity {
        name: "Boldrei",
        alignment: Alignment::LAWFUL_GOOD,
        domains: &[Domain::Life],
        pantheon: Pantheon::Eberron,
        symbols: &["Fire in a stone hearth"],
        titles: &["goddess of community and home"],
    },
    Deity {
        name: "Dol Arrah",
        alignment: Alignment::LAWFUL_GOOD,
        domains: &[Domain::Light, Domain::War],
        pantheon: Pantheon::Eberron,
        symbols: &["Rising sun"],
        titles: &["goddess of sunlight and honor"],
    },
    Deity {
        name: "Dol Dorn",
        alignment: Alignment::CHAOTIC_GOOD,
        domains: &[Domain::War],
        pantheon: Pantheon::Eberron,
        symbols: &["Longsword crossed over a shield"],
        titles: &["god of strength at arms"],
    },
    Deity {
        name: "Kol Korran",
        alignment: Alignment::NEUTRAL,
        domains: &[Domain::Trickery],
        pantheon: Pantheon::Eberron,
        symbols: &["Nine-sided gold coin"],
        titles: &["god of trade and wealth"],
    },
    Deity {
        name: "Olladra",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Life, Domain::Trickery],
        pantheon: Pantheon::Eberron,
        symbols: &["Domino"],
        titles: &["goddess of good fortune"],
    },
    Deity {
        name: "Onatar",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Knowledge],
        pantheon: Pantheon::Eberron,
        symbols: &["Crossed hammer and tongs"],
        titles: &["god of craft"],
    },
    Deity {
        name: "The Devourer",
        alignment: Alignment::NEUTRAL_EVIL,
        domains: &[Domain::Tempest],
        pantheon: Pantheon::Eberron,
        symbols: &["Bundle of five sharpened bones"],
        titles: &["god of nature's wrath"],
    },
    Deity {
        name: "The Fury",
        alignment: Alignment::NEUTRAL_EVIL,
        domains: &[Domain::War],
        pantheon: Pantheon::Eberron,
        symbols: &["Winged wyrm with woman's head and upper body"],
        titles: &["goddess of wrath and madness"],
    },
    Deity {
        name: "The Keeper",
        alignment: Alignment::NEUTRAL_EVIL,
        domains: &[Domain::Death],
        pantheon: Pantheon::Eberron,
        symbols: &["Dragonshard stone in the shape of a fang"],
        titles: &["god of greed and death"],
    },
    Deity {
        name: "The Mockery",
        alignment: Alignment::NEUTRAL_EVIL,
        domains: &[Domain::War],
        pantheon: Pantheon::Eberron,
        symbols: &["Five blood-spattered tools"],
        titles: &["god of violence and treachery"],
    },
    Deity {
        name: "The Shadow",
        alignment: Alignment::CHAOTIC_EVIL,
        domains: &[Domain::Knowledge],
        pantheon: Pantheon::Eberron,
        symbols: &["Obsidian tower"],
        titles: &["god of dark magic"],
    },
    Deity {
        name: "The Traveler",
        alignment: Alignment::CHAOTIC_NEUTRAL,
        domains: &[Domain::Knowledge, Domain::Trickery],
        pantheon: Pantheon::Eberron,
        symbols: &["Four crossed, rune-inscribed bones"],
        titles: &["deity of chaos and change"],
    },
    Deity {
        name: "The Silver Flame",
        alignment: Alignment::LAWFUL_GOOD,
        domains: &[Domain::Life, Domain::Light, Domain::War],
        pantheon: Pantheon::Eberron,
        symbols: &["Flame drawn on silver or molded from silver"],
        titles: &["deity of protection and good"],
    },
    Deity {
        name: "The Blood of Vol",
        alignment: Alignment::LAWFUL_NEUTRAL,
        domains: &[Domain::Death, Domain::Life],
        pantheon: Pantheon::Eberron,
        symbols: &["Stylized dragon skull on red teardrop gem"],
        titles: &["philosophy of immortality and undeath"],
    },
    Deity {
        name: "Cults of the Dragon Below",
        alignment: Alignment::NEUTRAL_EVIL,
        domains: &[Domain::Trickery],
        pantheon: Pantheon::Eberron,
        symbols: &["Varies"],
        titles: &["deities of madness"],
    },
    Deity {
        name: "The Path of Light",
        alignment: Alignment::LAWFUL_NEUTRAL,
        domains: &[Domain::Life, Domain::Light],
        pantheon: Pantheon::Eberron,
        symbols: &["Brilliant crystal"],
        titles: &["philosophy of light and self-improvement"],
    },
    Deity {
        name: "The Undying Court",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Knowledge, Domain::Life],
        pantheon: Pantheon::Eberron,
        symbols: &["Varies"],
        titles: &["elven ancestors"],
    },
    Deity {
        name: "The Spirits of the Past",
        alignment: Alignment::CHAOTIC_GOOD,
        domains: &[Domain::War],
        pantheon: Pantheon::Eberron,
        symbols: &["Varies"],
        titles: &["elven ancestors"],
    },
];
