use alignments::Alignment;

use crate::{Deity, Domain, Pantheon};

pub const EGYPTIAN: &[Deity] = &[
    Deity {
        name: "Re-Horakhty",
        alignment: Alignment::LAWFUL_GOOD,
        domains: &[Domain::Life, Domain::Light],
        pantheon: Pantheon::Egyptian,
        symbols: &["Solar disk encircled by serpent"],
        titles: &["god of the sun, ruler of the gods"],
    },
    Deity {
        name: "Anubis",
        alignment: Alignment::LAWFUL_NEUTRAL,
        domains: &[Domain::Death],
        pantheon: Pantheon::Egyptian,
        symbols: &["Black jackal"],
        titles: &["god of judgment and death"],
    },
    Deity {
        name: "Apep",
        alignment: Alignment::NEUTRAL_EVIL,
        domains: &[Domain::Trickery],
        pantheon: Pantheon::Egyptian,
        symbols: &["Flaming snake"],
        titles: &["god of evil, fire, and serpents"],
    },
    Deity {
        name: "Bast",
        alignment: Alignment::CHAOTIC_GOOD,
        domains: &[Domain::War],
        pantheon: Pantheon::Egyptian,
        symbols: &["Cat"],
        titles: &["goddess of cats and vengeance"],
    },
    Deity {
        name: "Bes",
        alignment: Alignment::CHAOTIC_NEUTRAL,
        domains: &[Domain::Trickery],
        pantheon: Pantheon::Egyptian,
        symbols: &["Image of the misshapen deity"],
        titles: &["god of luck and music"],
    },
    Deity {
        name: "Hathor",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Life, Domain::Light],
        pantheon: Pantheon::Egyptian,
        symbols: &["Horned cow's head with lunar disk"],
        titles: &["goddess of love, music, and motherhood"],
    },
    Deity {
        name: "Imhotep",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Knowledge],
        pantheon: Pantheon::Egyptian,
        symbols: &["Step pyramid"],
        titles: &["god of crafts and medicine"],
    },
    Deity {
        name: "Isis",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Knowledge, Domain::Life],
        pantheon: Pantheon::Egyptian,
        symbols: &["Ankh and star"],
        titles: &["goddess of fertility and magic"],
    },
    Deity {
        name: "Nephthys",
        alignment: Alignment::CHAOTIC_GOOD,
        domains: &[Domain::Death],
        pantheon: Pantheon::Egyptian,
        symbols: &["Horns around a lunar disk"],
        titles: &["goddess of death and grief"],
    },
    Deity {
        name: "Osiris",
        alignment: Alignment::LAWFUL_GOOD,
        domains: &[Domain::Life, Domain::Nature],
        pantheon: Pantheon::Egyptian,
        symbols: &["Crook and flail"],
        titles: &["god of nature and the underworld"],
    },
    Deity {
        name: "Ptah",
        alignment: Alignment::LAWFUL_NEUTRAL,
        domains: &[Domain::Knowledge],
        pantheon: Pantheon::Egyptian,
        symbols: &["Bull"],
        titles: &["god of crafts, knowledge, and secrets"],
    },
    Deity {
        name: "Set",
        alignment: Alignment::CHAOTIC_EVIL,
        domains: &[Domain::Death, Domain::Tempest, Domain::Trickery],
        pantheon: Pantheon::Egyptian,
        symbols: &["Coiled cobra"],
        titles: &["god of darkness and desert storms"],
    },
    Deity {
        name: "Sobek",
        alignment: Alignment::LAWFUL_EVIL,
        domains: &[Domain::Nature, Domain::Tempest],
        pantheon: Pantheon::Egyptian,
        symbols: &["Crocodile head with horns and plumes"],
        titles: &["god of water and crocodiles"],
    },
    Deity {
        name: "Thoth",
        alignment: Alignment::NEUTRAL,
        domains: &[Domain::Knowledge],
        pantheon: Pantheon::Egyptian,
        symbols: &["Ibis"],
        titles: &["god of knowledge and wisdom"],
    },
];
