use alignments::{Alignment, Attitude, Morality};

use crate::{Deity, Domain, Pantheon};

pub const ELVEN: &[Deity] = &[
    Deity {
        name: "Aerdrie Faenya",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Good),
        domains: &[Domain::Life, Domain::Tempest, Domain::Trickery],
        pantheon: Pantheon::Elven,
        symbols: &["Bird silhouetted against a cloud"],
        titles: &[
            "goddess of the sky",
            "wild goddess of the winds and weather",
            "patron of the avariel",
            "goddess of air, rain, fertility, and birth",
        ],
    },
    Deity {
        name: "Angharradh",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Good),
        domains: &[Domain::Knowledge, Domain::Life, Domain::War],
        pantheon: Pantheon::Elven,
        symbols: &[
            "Triangle with three interlocking circles within",
            "Three interlocking circles",
        ],
        titles: &[
            "triple goddess of wisdom and protection",
            "the fierce mother-protector of the elf people",
            "goddess of wisdom, growth, and protection",
        ],
    },
    Deity {
        name: "Alathrien Druanna",
        alignment: Alignment::new(Attitude::Neutral, Morality::Neutral),
        domains: &[Domain::Arcana, Domain::Knowledge],
        pantheon: Pantheon::Elven,
        symbols: &["A quill or glyph"],
        titles: &["deity of runes, writing, and spellcasting"],
    },
    Deity {
        name: "Alobal Lorfiril",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Good),
        domains: &[Domain::Life, Domain::Trickery],
        pantheon: Pantheon::Elven,
        symbols: &["Wine Glass"],
        titles: &["deity of revelry and mirth"],
    },
    Deity {
        name: "Araleth Letheranil",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Good),
        domains: &[Domain::Knowledge, Domain::Light],
        pantheon: Pantheon::Elven,
        symbols: &["Shaft of light"],
        titles: &["deity of light, stars, and revelations"],
    },
    Deity {
        name: "Corellon Larathian",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Good),
        domains: &[Domain::Arcana, Domain::Life, Domain::Light, Domain::War],
        pantheon: Pantheon::Elven,
        symbols: &["Crescent moon", "quarter moon", "starburst"],
        titles: &[
            "god of art and magic",
            "god of elves, magic, poetry, rulership, and warcraft",
            "Primary god of elves",
        ],
    },
    Deity {
        name: "Darahl Tilvenar",
        alignment: Alignment::new(Attitude::Lawful, Morality::Neutral),
        domains: &[Domain::Forge, Domain::Light],
        pantheon: Pantheon::Elven,
        symbols: &["Flame between hands"],
        titles: &["deity of fire, earth, and metalwork"],
    },
    Deity {
        name: "Deep Sashelas",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Good),
        domains: &[Domain::Knowledge, Domain::Nature, Domain::Tempest],
        pantheon: Pantheon::Elven,
        symbols: &["Dolphin"],
        titles: &[
            "god of the sea",
            "lord of the sea elves and of dolphins",
            "god of creativity, knowledge, and the sea",
        ],
    },
    Deity {
        name: "Elebrin Liothiel",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Good),
        domains: &[Domain::Life, Domain::Nature],
        pantheon: Pantheon::Elven,
        symbols: &["Acorn"],
        titles: &["deity of abundance, gardens, and the harvest"],
    },
    Deity {
        name: "Erevan Ilesere",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Neutral),
        domains: &[Domain::Trickery],
        pantheon: Pantheon::Elven,
        symbols: &["Asymmetrical eight-armed star", "Asymmetrical starburst"],
        titles: &[
            "god of mischief",
            "trickster-god",
            "god of mischief and change",
        ],
    },
    Deity {
        name: "Fenmarel Mestarine",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Neutral),
        domains: &[Domain::Nature, Domain::Trickery],
        pantheon: Pantheon::Elven,
        symbols: &["Two peering elven eyes"],
        titles: &["god of outcasts and solitude"],
    },
    Deity {
        name: "Gadhelyn",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Neutral),
        domains: &[Domain::Nature, Domain::Trickery],
        pantheon: Pantheon::Elven,
        symbols: &["Leaf-shaped arrowhead"],
        titles: &["deity of independence and outlawry"],
    },
    Deity {
        name: "Hanali Celanil",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Good),
        domains: &[Domain::Life],
        pantheon: Pantheon::Elven,
        symbols: &["Golden heart"],
        titles: &[
            "goddess of love, beauty, art, and enchantment",
            "the Winsome Rose",
        ],
    },
    Deity {
        name: "Kirith Sotheril",
        alignment: Alignment::new(Attitude::Neutral, Morality::Good),
        domains: &[Domain::Knowledge, Domain::Trickery],
        pantheon: Pantheon::Elven,
        symbols: &["Rainbow sphere"],
        titles: &["deity of divination and illusion"],
    },
    Deity {
        name: "Labelas Enoreth",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Good),
        domains: &[Domain::Arcana, Domain::Knowledge, Domain::Life],
        pantheon: Pantheon::Elven,
        symbols: &["Setting sun"],
        titles: &[
            "god of time, history, and philosophy",
            "the philosopher god",
            "god of time, history, and memory",
        ],
    },
    Deity {
        name: "Melira Taralen",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Good),
        domains: &[Domain::Knowledge, Domain::Life, Domain::Trickery],
        pantheon: Pantheon::Elven,
        symbols: &["Lute"],
        titles: &["deity of poetry and songs"],
    },
    Deity {
        name: "Mythrien Sarath",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Good),
        domains: &[Domain::Arcana, Domain::Forge, Domain::Knowledge],
        pantheon: Pantheon::Elven,
        symbols: &["Row of three intertwined rings"],
        titles: &["deity of abjuration and mythals"],
    },
    Deity {
        name: "Naralis Analor",
        alignment: Alignment::new(Attitude::Neutral, Morality::Good),
        domains: &[Domain::Life, Domain::Grave],
        pantheon: Pantheon::Elven,
        symbols: &["White dove"],
        titles: &["deity of healing, suffering, and death"],
    },
    Deity {
        name: "Rellavar Danuvien",
        alignment: Alignment::new(Attitude::Neutral, Morality::Good),
        domains: &[Domain::Tempest],
        pantheon: Pantheon::Elven,
        symbols: &["Spear between two circles"],
        titles: &["deity of winter and harsh weather"],
    },
    Deity {
        name: "Rillifane Rallathil",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Good),
        domains: &[Domain::Nature],
        pantheon: Pantheon::Elven,
        symbols: &["Oak"],
        titles: &[
            "god of nature",
            "god of the woodlands and wild places",
            "father of the wood elves",
            "protector of druids",
            "god of nature, beasts, and the seasons",
        ],
    },
    Deity {
        name: "Sarula Iliene",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Good),
        domains: &[Domain::Tempest, Domain::Trickery],
        pantheon: Pantheon::Elven,
        symbols: &["Three lines symbolizing waves"],
        titles: &["deity of lakes and streams"],
    },
    Deity {
        name: "Sehanine Moonbow",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Good),
        domains: &[Domain::Grave, Domain::Knowledge, Domain::Light],
        pantheon: Pantheon::Elven,
        symbols: &["Full moon under a moonbow", "crescent moon"],
        titles: &[
            "goddess of the moon",
            "goddess of divination, dreams, travel, and death",
            "goddess of all life's mysteries, including mysticism, prophecy, death, and dreams",
            "the Moonlit Mystery",
        ],
    },
    Deity {
        name: "Shevarash",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Neutral),
        domains: &[Domain::War],
        pantheon: Pantheon::Elven,
        symbols: &["Broken arrow over a tear"],
        titles: &["god of vengeance", "god of vengeance, loss, and hatred"],
    },
    Deity {
        name: "Solonor Thelandira",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Good),
        domains: &[Domain::Nature, Domain::War],
        pantheon: Pantheon::Elven,
        symbols: &["Silver arrow with green fletching"],
        titles: &[
            "god of hunting, archery, and woodcraft",
            "god of archery, hunting, and survival",
        ],
    },
    Deity {
        name: "Tarsellis Meunniduin",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Neutral),
        domains: &[Domain::Nature, Domain::Tempest],
        pantheon: Pantheon::Elven,
        symbols: &["Mountain with a river"],
        titles: &["deity of mountains, rivers, and wild places"],
    },
    Deity {
        name: "Tethrin Varald\u{e9}",
        alignment: Alignment::new(Attitude::Neutral, Morality::Good),
        domains: &[Domain::War],
        pantheon: Pantheon::Elven,
        symbols: &["Crossed swords beneath a quarter moon and above a full moon"],
        titles: &["deity of battle, and sword fighting"],
    },
    Deity {
        name: "Vandria Gilmadrith",
        alignment: Alignment::new(Attitude::Lawful, Morality::Neutral),
        domains: &[Domain::Grave, Domain::War],
        pantheon: Pantheon::Elven,
        symbols: &["Weeping eye"],
        titles: &["deity of war, grief, justice, and vigilance"],
    },
    Deity {
        name: "Ye'Cind",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Good),
        domains: &[Domain::Life, Domain::Trickery],
        pantheon: Pantheon::Elven,
        symbols: &["Recorder"],
        titles: &["deity of music and enchantment"],
    },
    Deity {
        name: "Zandilar",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Neutral),
        domains: &[Domain::Life],
        pantheon: Pantheon::Elven,
        symbols: &["Lips"],
        titles: &["deity of romance, lust, and dance"],
    },
];
