use alignments::Alignment;

use crate::{Deity, Domain, Pantheon};

pub const GNOMISH: &[Deity] = &[
    Deity {
        name: "Baervan Wildwanderer",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Nature],
        pantheon: Pantheon::Gnomish,
        symbols: &["Face of a raccoon"],
        titles: &["god of forests and woodlands", "god of woodlands"],
    },
    Deity {
        name: "Baravar Cloakshadow",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Arcana, Domain::Trickery],
        pantheon: Pantheon::Gnomish,
        symbols: &["Dagger against a hooded cloak"],
        titles: &["god of illusion and deception", "Sly One"],
    },
    Deity {
        name: "Bleredd",
        alignment: Alignment::NEUTRAL,
        domains: &[Domain::Forge, Domain::Light],
        pantheon: Pantheon::Gnomish,
        symbols: &["Iron mule"],
        titles: &["deity of labor and craft"],
    },
    Deity {
        name: "Callarduran Smoothhands",
        alignment: Alignment::NEUTRAL,
        domains: &[Domain::Knowledge, Domain::Nature],
        pantheon: Pantheon::Gnomish,
        symbols: &["Golden signet ring with a six-pointed star"],
        titles: &["god of mining and carving stone"],
    },
    Deity {
        name: "Flandal Steelskin",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Forge, Domain::Knowledge],
        pantheon: Pantheon::Gnomish,
        symbols: &["Flaming hammer"],
        titles: &[
            "god of metalwork",
            "god of mining and smithcraft",
            "god of physical improvement and good health",
            "the Steelsmith",
        ],
    },
    Deity {
        name: "Gaerdal Ironhand",
        alignment: Alignment::LAWFUL_GOOD,
        domains: &[Domain::War],
        pantheon: Pantheon::Gnomish,
        symbols: &["Iron band"],
        titles: &["god of protection", "god of war, vigilance, and defense"],
    },
    Deity {
        name: "Garl Glittergold",
        alignment: Alignment::LAWFUL_GOOD,
        domains: &[Domain::Trickery],
        pantheon: Pantheon::Gnomish,
        symbols: &["Gold nugget"],
        titles: &[
            "god of humor, gemcutting, protection, and trickery",
            "god of trickery and wiles",
            "the Watchful Protector",
            "the king of the gnomish gods",
            "Primary god of gnomes",
        ],
    },
    Deity {
        name: "Gelf Darkhearth",
        alignment: Alignment::CHAOTIC_NEUTRAL,
        domains: &[Domain::War],
        pantheon: Pantheon::Gnomish,
        symbols: &["Broken anvil"],
        titles: &["deity of frustration and destruction"],
    },
    Deity {
        name: "Nebelun",
        alignment: Alignment::CHAOTIC_GOOD,
        domains: &[Domain::Forge, Domain::Knowledge, Domain::Trickery],
        pantheon: Pantheon::Gnomish,
        symbols: &["Bellows and a lizard tail"],
        titles: &["god of invention and luck", "the Meddler"],
    },
    Deity {
        name: "Rill Cleverthrush",
        alignment: Alignment::LAWFUL_NEUTRAL,
        domains: &[Domain::Knowledge],
        pantheon: Pantheon::Gnomish,
        symbols: &["Interlocking gears"],
        titles: &["deity of law and thought"],
    },
    Deity {
        name: "Segojan Earthcaller",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Grave, Domain::Light],
        pantheon: Pantheon::Gnomish,
        symbols: &["Glowing gemstone"],
        titles: &[
            "god of earth and the dead",
            "god of the wilds beneath the earth",
            "god of the burrows",
        ],
    },
    Deity {
        name: "Sheyanna Flaxenstrand",
        alignment: Alignment::CHAOTIC_GOOD,
        domains: &[Domain::Light],
        pantheon: Pantheon::Gnomish,
        symbols: &["Two silver goblets"],
        titles: &["deity of love, beauty, and passion"],
    },
    Deity {
        name: "Urdlen",
        alignment: Alignment::CHAOTIC_EVIL,
        domains: &[Domain::Death, Domain::War],
        pantheon: Pantheon::Gnomish,
        symbols: &["White clawed mole emerging from ground"],
        titles: &[
            "god of greed and murder",
            "great-clawed god of bloodlust and evil, of greed and uncontrolled impulses",
        ],
    },
];
