use alignments::Alignment;

use crate::{Deity, Domain, Pantheon};

pub const GREEK: &[Deity] = &[
    Deity {
        name: "Zeus",
        alignment: Alignment::NEUTRAL,
        domains: &[Domain::Tempest],
        pantheon: Pantheon::Greek,
        symbols: &["Fist full of lightning bolts"],
        titles: &["god of the sky, ruler of the gods"],
    },
    Deity {
        name: "Aphrodite",
        alignment: Alignment::CHAOTIC_GOOD,
        domains: &[Domain::Light],
        pantheon: Pantheon::Greek,
        symbols: &["Sea shell"],
        titles: &["goddess of love and beauty"],
    },
    Deity {
        name: "Apollo",
        alignment: Alignment::CHAOTIC_GOOD,
        domains: &[Domain::Knowledge, Domain::Life, Domain::Light],
        pantheon: Pantheon::Greek,
        symbols: &["Lyre"],
        titles: &["god of light, music, and healing"],
    },
    Deity {
        name: "Ares",
        alignment: Alignment::CHAOTIC_EVIL,
        domains: &[Domain::War],
        pantheon: Pantheon::Greek,
        symbols: &["Spear"],
        titles: &["god of war and strife"],
    },
    Deity {
        name: "Artemis",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Life, Domain::Nature],
        pantheon: Pantheon::Greek,
        symbols: &["Bow and arrow on lunar disk"],
        titles: &["goddess of hunting and childbirth"],
    },
    Deity {
        name: "Athena",
        alignment: Alignment::LAWFUL_GOOD,
        domains: &[Domain::Knowledge, Domain::War],
        pantheon: Pantheon::Greek,
        symbols: &["Owl"],
        titles: &["goddess of wisdom and civilization"],
    },
    Deity {
        name: "Demeter",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Life],
        pantheon: Pantheon::Greek,
        symbols: &["Mare's head"],
        titles: &["goddess of agriculture"],
    },
    Deity {
        name: "Dionysus",
        alignment: Alignment::CHAOTIC_NEUTRAL,
        domains: &[Domain::Life],
        pantheon: Pantheon::Greek,
        symbols: &["Thyrsus (staff tipped with pine cone)"],
        titles: &["god of mirth and wine"],
    },
    Deity {
        name: "Hades",
        alignment: Alignment::LAWFUL_EVIL,
        domains: &[Domain::Death],
        pantheon: Pantheon::Greek,
        symbols: &["Black ram"],
        titles: &["god of the underworld"],
    },
    Deity {
        name: "Hecate",
        alignment: Alignment::CHAOTIC_EVIL,
        domains: &[Domain::Knowledge, Domain::Trickery],
        pantheon: Pantheon::Greek,
        symbols: &["Setting moon"],
        titles: &["goddess of magic and the moon"],
    },
    Deity {
        name: "Hephaestus",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Knowledge],
        pantheon: Pantheon::Greek,
        symbols: &["Hammer and anvil"],
        titles: &["god of smithing and craft"],
    },
    Deity {
        name: "Hera",
        alignment: Alignment::CHAOTIC_NEUTRAL,
        domains: &[Domain::Trickery],
        pantheon: Pantheon::Greek,
        symbols: &["Fan of peacock feathers"],
        titles: &["goddess of marriage and intrigue"],
    },
    Deity {
        name: "Hercules",
        alignment: Alignment::CHAOTIC_GOOD,
        domains: &[Domain::Tempest, Domain::War],
        pantheon: Pantheon::Greek,
        symbols: &["Lion's head"],
        titles: &["god of strength and adventure"],
    },
    Deity {
        name: "Hermes",
        alignment: Alignment::CHAOTIC_GOOD,
        domains: &[Domain::Trickery],
        pantheon: Pantheon::Greek,
        symbols: &["Caduceus (winged staff and serpents)"],
        titles: &["god of travel and commerce"],
    },
    Deity {
        name: "Hestia",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Life],
        pantheon: Pantheon::Greek,
        symbols: &["Hearth"],
        titles: &["goddess of home and family"],
    },
    Deity {
        name: "Nike",
        alignment: Alignment::LAWFUL_NEUTRAL,
        domains: &[Domain::War],
        pantheon: Pantheon::Greek,
        symbols: &["Winged woman"],
        titles: &["goddess of victory"],
    },
    Deity {
        name: "Pan",
        alignment: Alignment::CHAOTIC_NEUTRAL,
        domains: &[Domain::Nature],
        pantheon: Pantheon::Greek,
        symbols: &["Syrinx (pan pipes)"],
        titles: &["god of nature"],
    },
    Deity {
        name: "Poseidon",
        alignment: Alignment::CHAOTIC_NEUTRAL,
        domains: &[Domain::Tempest],
        pantheon: Pantheon::Greek,
        symbols: &["Trident"],
        titles: &["god of the sea and earthquakes"],
    },
    Deity {
        name: "Tyche",
        alignment: Alignment::NEUTRAL,
        domains: &[Domain::Trickery],
        pantheon: Pantheon::Greek,
        symbols: &["Red pentagram"],
        titles: &["goddess of good fortune"],
    },
];
