use alignments::{Alignment, Attitude, Morality};

use crate::{Deity, Domain, Pantheon};

pub const GREYHAWK: &[Deity] = &[
    Deity {
        name: "Beory",
        alignment: Alignment::new(Attitude::Neutral, Morality::Neutral),
        domains: &[Domain::Nature],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Green disk"],
        titles: &["goddess of nature"],
    },
    Deity {
        name: "Boccob",
        alignment: Alignment::new(Attitude::Neutral, Morality::Neutral),
        domains: &[Domain::Knowledge],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Eye within a pentagram"],
        titles: &["god of magic"],
    },
    Deity {
        name: "Celestian",
        alignment: Alignment::new(Attitude::Neutral, Morality::Neutral),
        domains: &[Domain::Knowledge],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Arc of seven stars inside a circle"],
        titles: &["god of stars and wanderers"],
    },
    Deity {
        name: "Ehlonna",
        alignment: Alignment::new(Attitude::Neutral, Morality::Good),
        domains: &[Domain::Life, Domain::Nature],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Unicorn horn"],
        titles: &["goddess of woodlands"],
    },
    Deity {
        name: "Erythnul",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Evil),
        domains: &[Domain::War],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Blood drop"],
        titles: &["god of envy and slaughter"],
    },
    Deity {
        name: "Fharlanghn",
        alignment: Alignment::new(Attitude::Neutral, Morality::Good),
        domains: &[Domain::Knowledge, Domain::Trickery],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Circle crossed by a curved horizon line"],
        titles: &["god of horizons and travel"],
    },
    Deity {
        name: "Heironeous",
        alignment: Alignment::new(Attitude::Lawful, Morality::Good),
        domains: &[Domain::War],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Lightning bolt"],
        titles: &["god of chivalry and valor"],
    },
    Deity {
        name: "Hextor",
        alignment: Alignment::new(Attitude::Lawful, Morality::Evil),
        domains: &[Domain::War],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Six arrows facing downward in a fan"],
        titles: &["god of war and discord"],
    },
    Deity {
        name: "Kord",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Good),
        domains: &[Domain::Tempest, Domain::War],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Four spears and four maces radiating out from a central point"],
        titles: &["god of athletics and sport"],
    },
    Deity {
        name: "Incabulos",
        alignment: Alignment::new(Attitude::Neutral, Morality::Evil),
        domains: &[Domain::Death],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Reptilian eye with a horizontal diamond"],
        titles: &["god of plague and famine"],
    },
    Deity {
        name: "Istus",
        alignment: Alignment::new(Attitude::Neutral, Morality::Neutral),
        domains: &[Domain::Knowledge],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Weaver's spindle with three strands"],
        titles: &["goddess of fate and destiny"],
    },
    Deity {
        name: "Iuz",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Evil),
        domains: &[Domain::Death],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Grinning human skull"],
        titles: &["god of pain and oppression"],
    },
    Deity {
        name: "Nerull",
        alignment: Alignment::new(Attitude::Neutral, Morality::Evil),
        domains: &[Domain::Death],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Skull with either a sickle or a scythe"],
        titles: &["god of death"],
    },
    Deity {
        name: "Obad-Hai",
        alignment: Alignment::new(Attitude::Neutral, Morality::Neutral),
        domains: &[Domain::Nature],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Oak leaf and acorn"],
        titles: &["god of nature"],
    },
    Deity {
        name: "Olidammara",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Neutral),
        domains: &[Domain::Trickery],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Laughing mask"],
        titles: &["god of revelry"],
    },
    Deity {
        name: "Pelor",
        alignment: Alignment::new(Attitude::Neutral, Morality::Good),
        domains: &[Domain::Life, Domain::Light],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Sun"],
        titles: &["god of the sun and healing"],
    },
    Deity {
        name: "Pholtus",
        alignment: Alignment::new(Attitude::Lawful, Morality::Good),
        domains: &[Domain::Light],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Silver sun or full moon partially eclipsed by a smaller crescent moon"],
        titles: &["god of light and law"],
    },
    Deity {
        name: "Ralishaz",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Neutral),
        domains: &[Domain::Trickery],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Three bone fate-casting sticks"],
        titles: &["god of ill luck and insanity"],
    },
    Deity {
        name: "Rao",
        alignment: Alignment::new(Attitude::Lawful, Morality::Good),
        domains: &[Domain::Knowledge],
        pantheon: Pantheon::Greyhawk,
        symbols: &["White heart"],
        titles: &["god of peace and reason"],
    },
    Deity {
        name: "St. Cuthbert",
        alignment: Alignment::new(Attitude::Lawful, Morality::Neutral),
        domains: &[Domain::Knowledge],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Circle at the center of a starburst of lines"],
        titles: &["god of common sense and zeal"],
    },
    Deity {
        name: "Tharizdun",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Evil),
        domains: &[Domain::Trickery],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Dark spiral or inverted ziggurat"],
        titles: &["god of eternal darkness"],
    },
    Deity {
        name: "Trithereon",
        alignment: Alignment::new(Attitude::Chaotic, Morality::Good),
        domains: &[Domain::War],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Triskelion"],
        titles: &["god of liberty and retribution"],
    },
    Deity {
        name: "Ulaa",
        alignment: Alignment::new(Attitude::Lawful, Morality::Good),
        domains: &[Domain::Life, Domain::War],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Mountain with a circle at its heart"],
        titles: &["goddess of hills and mountains"],
    },
    Deity {
        name: "Vecna",
        alignment: Alignment::new(Attitude::Neutral, Morality::Evil),
        domains: &[Domain::Knowledge],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Hand with eye in the palm"],
        titles: &["god of evil secrets"],
    },
    Deity {
        name: "Wee Jas",
        alignment: Alignment::new(Attitude::Lawful, Morality::Neutral),
        domains: &[Domain::Death, Domain::Knowledge],
        pantheon: Pantheon::Greyhawk,
        symbols: &["Red skull in front of fireball"],
        titles: &["goddess of magic and death"],
    },
];
