use alignments::Alignment;

use crate::{Deity, Domain, Pantheon};

pub const NORSE: &[Deity] = &[
    Deity {
        name: "Odin",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Knowledge, Domain::War],
        pantheon: Pantheon::Norse,
        symbols: &["Watching blue eye"],
        titles: &["god of knowledge and war"],
    },
    Deity {
        name: "Aegir",
        alignment: Alignment::NEUTRAL_EVIL,
        domains: &[Domain::Tempest],
        pantheon: Pantheon::Norse,
        symbols: &["Rough ocean waves"],
        titles: &["god of the sea and storms"],
    },
    Deity {
        name: "Balder",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Life, Domain::Light],
        pantheon: Pantheon::Norse,
        symbols: &["Gem-encrusted silver chalice"],
        titles: &["god of beauty and poetry"],
    },
    Deity {
        name: "Forseti",
        alignment: Alignment::NEUTRAL,
        domains: &[Domain::Light],
        pantheon: Pantheon::Norse,
        symbols: &["Head of a bearded man"],
        titles: &["god of justice and law"],
    },
    Deity {
        name: "Frey",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Life, Domain::Light],
        pantheon: Pantheon::Norse,
        symbols: &["Ice-blue greatsword"],
        titles: &["god of fertility and the sun"],
    },
    Deity {
        name: "Freya",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Life],
        pantheon: Pantheon::Norse,
        symbols: &["Falcon"],
        titles: &["goddess of fertility and love"],
    },
    Deity {
        name: "Frigga",
        alignment: Alignment::NEUTRAL,
        domains: &[Domain::Life, Domain::Light],
        pantheon: Pantheon::Norse,
        symbols: &["Cat"],
        titles: &["goddess of birth and fertility"],
    },
    Deity {
        name: "Heimdall",
        alignment: Alignment::LAWFUL_GOOD,
        domains: &[Domain::Light, Domain::War],
        pantheon: Pantheon::Norse,
        symbols: &["Curling musical horn"],
        titles: &["god of watchfulness and loyalty"],
    },
    Deity {
        name: "Hel",
        alignment: Alignment::NEUTRAL_EVIL,
        domains: &[Domain::Death],
        pantheon: Pantheon::Norse,
        symbols: &["Woman's face, rotting on one side"],
        titles: &["goddess of the underworld"],
    },
    Deity {
        name: "Hermod",
        alignment: Alignment::CHAOTIC_NEUTRAL,
        domains: &[Domain::Trickery],
        pantheon: Pantheon::Norse,
        symbols: &["Winged scroll"],
        titles: &["god of luck"],
    },
    Deity {
        name: "Loki",
        alignment: Alignment::CHAOTIC_EVIL,
        domains: &[Domain::Trickery],
        pantheon: Pantheon::Norse,
        symbols: &["Flame"],
        titles: &["god of thieves and trickery"],
    },
    Deity {
        name: "Njord",
        alignment: Alignment::NEUTRAL_GOOD,
        domains: &[Domain::Nature, Domain::Tempest],
        pantheon: Pantheon::Norse,
        symbols: &["Gold coin"],
        titles: &["god of sea and wind"],
    },
    Deity {
        name: "Odur",
        alignment: Alignment::CHAOTIC_GOOD,
        domains: &[Domain::Light],
        pantheon: Pantheon::Norse,
        symbols: &["Solar disk"],
        titles: &["god of light and the sun"],
    },
    Deity {
        name: "Sif",
        alignment: Alignment::CHAOTIC_GOOD,
        domains: &[Domain::War],
        pantheon: Pantheon::Norse,
        symbols: &["Upraised sword"],
        titles: &["goddess of war"],
    },
    Deity {
        name: "Skadi",
        alignment: Alignment::NEUTRAL,
        domains: &[Domain::Nature],
        pantheon: Pantheon::Norse,
        symbols: &["Mountain peak"],
        titles: &["god of earth and mountains"],
    },
    Deity {
        name: "Surtur",
        alignment: Alignment::LAWFUL_EVIL,
        domains: &[Domain::War],
        pantheon: Pantheon::Norse,
        symbols: &["Flaming sword"],
        titles: &["god of fire giants and war"],
    },
    Deity {
        name: "Thor",
        alignment: Alignment::CHAOTIC_GOOD,
        domains: &[Domain::Tempest, Domain::War],
        pantheon: Pantheon::Norse,
        symbols: &["Hammer"],
        titles: &["god of storms and thunder"],
    },
    Deity {
        name: "Thrym",
        alignment: Alignment::CHAOTIC_EVIL,
        domains: &[Domain::War],
        pantheon: Pantheon::Norse,
        symbols: &["White double-bladed axe"],
        titles: &["god of frost giants and cold"],
    },
    Deity {
        name: "Tyr",
        alignment: Alignment::LAWFUL_NEUTRAL,
        domains: &[Domain::Knowledge, Domain::War],
        pantheon: Pantheon::Norse,
        symbols: &["Sword"],
        titles: &["god of courage and strategy"],
    },
    Deity {
        name: "Uller",
        alignment: Alignment::CHAOTIC_NEUTRAL,
        domains: &[Domain::Nature],
        pantheon: Pantheon::Norse,
        symbols: &["Longbow"],
        titles: &["god of hunting and winter"],
    },
];
